"""Crypto spike-reversion strategy.

Evaluates crypto signals where a sharp short-horizon price spike has occurred
and a mean-reversion entry is favorable.  Uses 5m/30m/2h price movement
context from the crypto worker to validate direction alignment and reversion
shape before sizing with Kelly or other configurable policies.

This is an evaluate-only strategy — signals are generated by the crypto
worker, not by a detect() scan.
"""

from __future__ import annotations

import logging
from typing import Any

from services.strategies.base import BaseStrategy, DecisionCheck, StrategyDecision, ExitDecision
from services.data_events import DataEvent
from services.quality_filter import QualityFilterOverrides
from utils.converters import to_float, to_confidence
from utils.signal_helpers import signal_payload, live_move, selected_probability
from services.trader_orchestrator.strategies.sizing import compute_position_size

logger = logging.getLogger(__name__)


class CryptoSpikeReversionStrategy(BaseStrategy):
    """Spike-reversion execution using live 5m/30m/2h movement context."""

    strategy_type = "crypto_spike_reversion"
    name = "Crypto Spike Reversion"
    description = "Spike-reversion execution using live 5m/30m/2h movement context"
    mispricing_type = "within_market"
    source_key = "crypto"
    worker_affinity = "crypto"
    market_categories = ["crypto"]
    subscriptions = ["crypto_update"]

    quality_filter_overrides = QualityFilterOverrides(
        min_roi=1.0,
        max_resolution_months=0.1,
    )

    default_config = {
        "min_edge_percent": 2.8,
        "min_confidence": 0.44,
        "min_abs_move_5m": 1.8,
        "max_abs_move_2h": 14.0,
        "base_size_usd": 20.0,
        "max_size_usd": 120.0,
        "take_profit_pct": 8.0,
    }

    async def on_event(self, event: DataEvent) -> list:
        # Evaluate-only strategy: detection is handled by btc_eth_highfreq.
        return []

    def evaluate(self, signal: Any, context: dict[str, Any]) -> StrategyDecision:
        params = context.get("params") or {}
        payload = signal_payload(signal)
        live_market = context.get("live_market") or {}

        min_edge = to_float(params.get("min_edge_percent", 2.8), 2.8)
        min_conf = to_confidence(params.get("min_confidence", 0.44), 0.44)
        min_abs_move_5m = max(0.2, to_float(params.get("min_abs_move_5m", 1.8), 1.8))
        max_abs_move_2h = max(min_abs_move_5m, to_float(params.get("max_abs_move_2h", 14.0), 14.0))
        require_reversion_shape = bool(params.get("require_reversion_shape", True))

        base_size = max(1.0, to_float(params.get("base_size_usd", 20.0), 20.0))
        max_size = max(base_size, to_float(params.get("max_size_usd", 120.0), 120.0))
        sizing_policy = str(params.get("sizing_policy", "kelly") or "kelly")
        kelly_fractional_scale = to_float(params.get("kelly_fractional_scale", 0.45), 0.45)

        source = str(getattr(signal, "source", "") or "").strip().lower()
        direction = str(getattr(signal, "direction", "") or "").strip().lower()
        signal_type = str(getattr(signal, "signal_type", "") or "").strip().lower()

        edge = max(0.0, to_float(getattr(signal, "edge_percent", 0.0), 0.0))
        confidence = to_confidence(getattr(signal, "confidence", 0.0), 0.0)
        liquidity = max(0.0, to_float(getattr(signal, "liquidity", 0.0), 0.0))

        move_5m = live_move(live_market, "move_5m")
        move_30m = live_move(live_market, "move_30m")
        move_2h = live_move(live_market, "move_2h")

        # Direction alignment: signal direction must oppose the spike
        direction_alignment = False
        if move_5m is not None:
            if direction == "buy_yes":
                direction_alignment = move_5m <= -min_abs_move_5m
            elif direction == "buy_no":
                direction_alignment = move_5m >= min_abs_move_5m

        # Reversion shape: short-horizon impulse dominates the 30m trend
        shape_ok = True
        if require_reversion_shape:
            shape_ok = False
            if move_5m is not None and move_30m is not None:
                shape_ok = abs(move_5m) >= abs(move_30m) * 0.55
            if shape_ok and move_2h is not None:
                shape_ok = abs(move_2h) <= max_abs_move_2h

        origin_ok = bool(payload.get("strategy_origin") == "crypto_worker") or signal_type.startswith("crypto_worker")

        checks = [
            DecisionCheck("source", "Crypto source", source == "crypto", detail="Requires source=crypto."),
            DecisionCheck(
                "origin", "Crypto worker origin", origin_ok, detail="Requires worker-generated crypto signal."
            ),
            DecisionCheck("edge", "Edge threshold", edge >= min_edge, score=edge, detail=f"min={min_edge:.2f}"),
            DecisionCheck(
                "confidence",
                "Confidence threshold",
                confidence >= min_conf,
                score=confidence,
                detail=f"min={min_conf:.2f}",
            ),
            DecisionCheck(
                "direction_alignment",
                "Direction aligns with spike",
                direction_alignment,
                score=move_5m,
                detail=f"|move_5m| >= {min_abs_move_5m:.2f}% and opposes impulse",
            ),
            DecisionCheck(
                "reversion_shape",
                "Reversion shape",
                shape_ok,
                score=move_30m,
                detail=f"2h cap <= {max_abs_move_2h:.2f}%",
            ),
        ]

        score = (
            (edge * 0.55)
            + (confidence * 34.0)
            + (min(1.0, abs(move_5m or 0.0) / 8.0) * 8.0)
            + (min(1.0, liquidity / 20000.0) * 4.0)
        )

        if not all(check.passed for check in checks):
            return StrategyDecision(
                decision="skipped",
                reason="Crypto spike-reversion filters not met",
                score=score,
                checks=checks,
                payload={
                    "edge": edge,
                    "confidence": confidence,
                    "move_5m": move_5m,
                    "move_30m": move_30m,
                    "move_2h": move_2h,
                },
            )

        probability = selected_probability(signal, payload, direction)
        entry_price = to_float(getattr(signal, "entry_price", 0.0), 0.0)

        sizing = compute_position_size(
            base_size_usd=base_size,
            max_size_usd=max_size,
            edge_percent=edge,
            confidence=confidence,
            sizing_policy=sizing_policy,
            probability=probability,
            entry_price=entry_price if entry_price > 0 else None,
            kelly_fractional_scale=kelly_fractional_scale,
            liquidity_usd=liquidity,
            liquidity_cap_fraction=0.07,
        )

        return StrategyDecision(
            decision="selected",
            reason="Crypto spike-reversion signal selected",
            score=score,
            size_usd=float(sizing["size_usd"]),
            checks=checks,
            payload={
                "edge": edge,
                "confidence": confidence,
                "move_5m": move_5m,
                "move_30m": move_30m,
                "move_2h": move_2h,
                "sizing": sizing,
            },
        )

    def should_exit(self, position: Any, market_state: dict) -> ExitDecision:
        """Tight exit for spike reversion — short hold with explicit TP default."""
        config = getattr(position, "config", None) or {}
        config = dict(config)
        configured_tp = (getattr(self, "config", None) or {}).get("take_profit_pct", 8.0)
        try:
            default_tp = float(configured_tp)
        except (TypeError, ValueError):
            default_tp = 8.0
        config.setdefault("take_profit_pct", default_tp)
        position.config = config
        return self.default_exit_check(position, market_state)

    # ------------------------------------------------------------------
    # Platform gate hooks
    # ------------------------------------------------------------------

    def on_blocked(self, signal, reason: str, context: dict) -> None:
        logger.info("%s: signal blocked — %s (market=%s)", self.name, reason, getattr(signal, "market_id", "?"))

    def on_size_capped(self, original_size: float, capped_size: float, reason: str) -> None:
        logger.info("%s: size capped $%.0f → $%.0f — %s", self.name, original_size, capped_size, reason)
